"""State management helpers for the transcription source selection step"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/routes/core.ipynb.

# %% auto #0
__all__ = ['STEP_KEY', 'get_step_state', 'update_step_state', 'get_session_id_from_sess']

# %% ../../nbs/routes/core.ipynb #2910ebd3
from typing import Dict, Any, Optional

from cjm_workflow_state.state_store import SQLiteWorkflowStateStore
from ..models import SourceSelectState

# %% ../../nbs/routes/core.ipynb #13305708
STEP_KEY = "source_select"

# %% ../../nbs/routes/core.ipynb #ad03318b
def get_step_state(
    state_store: SQLiteWorkflowStateStore,  # Workflow state store
    workflow_id: str,  # Workflow identifier
    session_id: str,  # Session identifier
) -> SourceSelectState:  # Current step state (empty dict if not found)
    """Retrieve the source selection step state."""
    state = state_store.get_state(workflow_id, session_id)
    if not state:
        return {}
    return state.get("step_states", {}).get(STEP_KEY, {})

# %% ../../nbs/routes/core.ipynb #fdb6bdf4
def update_step_state(
    state_store: SQLiteWorkflowStateStore,  # Workflow state store
    workflow_id: str,  # Workflow identifier
    session_id: str,  # Session identifier
    **fields,  # Fields to update in the step state
) -> SourceSelectState:  # Updated step state
    """Update specific fields in the source selection step state."""
    state = state_store.get_state(workflow_id, session_id)
    if not state:
        state = {"step_states": {STEP_KEY: {}}}
    
    step_states = state.setdefault("step_states", {})
    step_state = step_states.setdefault(STEP_KEY, {})
    step_state.update(fields)
    
    state_store.update_state(workflow_id, session_id, state)
    return step_state

# %% ../../nbs/routes/core.ipynb #23d6a218
def get_session_id_from_sess(
    sess: Any  # Session object from FastHTML
) -> str:  # Session identifier string
    """Extract session ID from a FastHTML session object."""
    from cjm_fasthtml_interactions.core.state_store import get_session_id
    return get_session_id(sess)
