"""Router assembly — creates all sub-routers, populates URL bundle, returns unified interface"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/routes/init.ipynb.

# %% auto #0
__all__ = ['init_source_select_routers']

# %% ../../nbs/routes/init.ipynb #d4e5f6a7
from typing import Dict, List, Tuple, Callable

from fasthtml.common import APIRouter

from cjm_fasthtml_file_browser.core.config import FileBrowserConfig
from cjm_fasthtml_file_browser.providers.local import LocalFileSystemProvider
from cjm_workflow_state.state_store import SQLiteWorkflowStateStore

from ..models import SourceSelectUrls
from ..services.source_select import SourceSelectService
from .browser import init_browser_router
from .selection import init_selection_router
from .preview import init_preview_router
from .verify import init_verify_router

# %% ../../nbs/routes/init.ipynb #f6a7b8c9
def init_source_select_routers(
    state_store: SQLiteWorkflowStateStore,  # Workflow state store
    provider: LocalFileSystemProvider,  # File system provider
    browser_config: FileBrowserConfig,  # Browser configuration
    workflow_id: str,  # Workflow identifier
    service: SourceSelectService,  # Source select service (FFmpeg plugin)
    home_path: str = "",  # Home directory for nav buttons
    prefix: str = "/source_select",  # Base route prefix
) -> Tuple[List[APIRouter], SourceSelectUrls, Callable]:  # (routers, urls, render_panel_fn)
    """Initialize all source selection routers and populate URL bundle."""
    _home = home_path or provider.get_home_path()

    # Phase 1: Create empty URL bundle
    urls = SourceSelectUrls()

    # Phase 2: Initialize sub-routers
    fb_routers, render_panel_fn = init_browser_router(
        state_store=state_store,
        provider=provider,
        config=browser_config,
        workflow_id=workflow_id,
        urls=urls,
        home_path=_home,
        prefix=f"{prefix}/browser",
    )

    selection_router, selection_routes = init_selection_router(
        state_store=state_store,
        provider=provider,
        config=browser_config,
        workflow_id=workflow_id,
        urls=urls,
        home_path=_home,
        fb_routers=fb_routers,
        prefix=f"{prefix}/selection",
    )

    preview_router, preview_routes = init_preview_router(
        state_store=state_store,
        workflow_id=workflow_id,
        urls=urls,
        prefix=f"{prefix}/preview",
    )

    verify_router, verify_routes = init_verify_router(
        state_store=state_store,
        workflow_id=workflow_id,
        urls=urls,
        service=service,
        prefix=f"{prefix}/verify",
    )

    # Phase 3: Populate URL bundle
    urls.remove = selection_routes["remove"].to()
    urls.reorder = selection_routes["reorder"].to()
    urls.clear = selection_routes["clear"].to()
    urls.toggle_all = selection_routes["toggle_all"].to()
    urls.preview = preview_routes["preview"].to()
    urls.media_src = preview_routes["media_src"].to()
    urls.verify = verify_routes["verify"].to()

    # Phase 4: Merge and return
    routers = [fb_routers.browser, fb_routers.collection, selection_router, preview_router, verify_router]

    return routers, urls, render_panel_fn
