"""Route handlers for selection queue management (remove, reorder, clear)"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/routes/selection.ipynb.

# %% auto #0
__all__ = ['DEBUG_REORDER', 'init_selection_router']

# %% ../../nbs/routes/selection.ipynb #d9134d0d
from typing import Dict, Tuple, Callable
from pathlib import Path

from fasthtml.common import APIRouter

from cjm_fasthtml_file_browser.core.config import FileBrowserConfig
from cjm_fasthtml_file_browser.providers.local import LocalFileSystemProvider
from cjm_workflow_state.state_store import SQLiteWorkflowStateStore

from ..models import SourceSelectUrls
from cjm_transcription_source_select.routes.core import (
    get_step_state, update_step_state, get_session_id_from_sess
)
from ..components.selection_panel import render_selection_panel
from ..components.stats_panel import render_stats_panel
from cjm_transcription_source_select.components.file_browser_panel import (
    get_browser_state, sync_browser_selection, render_browser_panel
)

DEBUG_REORDER = False

# %% ../../nbs/routes/selection.ipynb #6faf1f42
def _render_oob_browser(
    state_store: SQLiteWorkflowStateStore,  # Workflow state store
    provider: LocalFileSystemProvider,  # File system provider
    config: FileBrowserConfig,  # Browser configuration
    workflow_id: str,  # Workflow identifier
    home_path: str,  # Home directory path
    urls: SourceSelectUrls,  # URL bundle
    session_id: str,  # Session identifier
    selected_files: list,  # Current selected files
    selected_folders: list = None,  # Current selected folders
):  # Browser panel with OOB attribute set
    """Render browser panel as OOB swap to update selection highlights."""
    step_state = get_step_state(state_store, workflow_id, session_id)
    browser_state = get_browser_state(step_state, home_path)
    sync_browser_selection(browser_state, selected_files, selected_folders)

    # Save updated browser state
    update_step_state(
        state_store, workflow_id, session_id,
        browser_state=browser_state.to_dict(),
    )

    browser = render_browser_panel(
        browser_state=browser_state,
        config=config,
        provider=provider,
        navigate_url=urls.navigate,
        select_url=urls.select,
        home_path=home_path,
    )
    browser.attrs["hx-swap-oob"] = "outerHTML"
    return browser

# %% ../../nbs/routes/selection.ipynb #66ceacad
def _handle_remove(
    state_store: SQLiteWorkflowStateStore,  # Workflow state store
    provider: LocalFileSystemProvider,  # File system provider
    config: FileBrowserConfig,  # Browser configuration
    workflow_id: str,  # Workflow identifier
    home_path: str,  # Home directory path
    urls: SourceSelectUrls,  # URL bundle
    sess,  # FastHTML session
    path: str,  # File path to remove
):  # (selection panel, OOB browser panel, OOB stats panel)
    """Remove a file from the selection."""
    session_id = get_session_id_from_sess(sess)
    step_state = get_step_state(state_store, workflow_id, session_id)
    selected_files = step_state.get("selected_files", [])
    selected_folders = step_state.get("selected_folders", [])

    selected_files = [f for f in selected_files if f["path"] != path]

    # Auto-deselect parent folder if no files from it remain
    parent = str(Path(path).parent)
    if parent in selected_folders:
        remaining = {f["path"] for f in selected_files}
        has_sibling = any(str(Path(p).parent) == parent for p in remaining)
        if not has_sibling:
            selected_folders = [f for f in selected_folders if f != parent]

    # Clean up extraction result for the removed file
    extraction_results = step_state.get("extraction_results", {})
    extraction_results.pop(path, None)

    update_step_state(
        state_store, workflow_id, session_id,
        selected_files=selected_files,
        selected_folders=selected_folders,
        extraction_results=extraction_results,
        verified=False,
        committed_audio_paths=[],
    )

    selection = render_selection_panel(selected_files, urls, extraction_results)
    browser_oob = _render_oob_browser(
        state_store, provider, config, workflow_id, home_path, urls,
        session_id, selected_files, selected_folders
    )
    stats_oob = render_stats_panel(selected_files, urls, extraction_results, verified=False)
    stats_oob.attrs["hx-swap-oob"] = "outerHTML"
    return selection, browser_oob, stats_oob

# %% ../../nbs/routes/selection.ipynb #35033565
async def _handle_reorder(
    state_store: SQLiteWorkflowStateStore,  # Workflow state store
    workflow_id: str,  # Workflow identifier
    urls: SourceSelectUrls,  # URL bundle
    request,  # FastHTML request
    sess,  # FastHTML session
):  # Rendered selection panel
    """Reorder selected files based on SortableJS drag result."""
    session_id = get_session_id_from_sess(sess)
    step_state = get_step_state(state_store, workflow_id, session_id)
    selected_files = step_state.get("selected_files", [])

    # Extract new order from form data (Hidden inputs sent in DOM order)
    form_data = await request.form()
    new_order_paths = form_data.getlist("item")

    if DEBUG_REORDER:
        print(f"\n[REORDER DEBUG] Handler called")
        print(f"  Content-Type: {request.headers.get('content-type', 'MISSING')}")
        print(f"  form_data keys: {list(form_data.keys())}")
        print(f"  form_data.getlist('item'): {new_order_paths}")
        print(f"  len(new_order_paths): {len(new_order_paths)}")
        print(f"  len(selected_files): {len(selected_files)}")
        print(f"  selected_files paths: {[f['path'] for f in selected_files]}")
        # Dump raw body for inspection
        body = await request.body()
        print(f"  Raw body ({len(body)} bytes): {body[:500]}")

    # Rebuild list in new order
    path_to_file = {f["path"]: f for f in selected_files}
    reordered = [path_to_file[p] for p in new_order_paths if p in path_to_file]

    # Add any files not in the form data (shouldn't happen, but safe)
    reordered_paths = {f["path"] for f in reordered}
    for f in selected_files:
        if f["path"] not in reordered_paths:
            reordered.append(f)

    if DEBUG_REORDER:
        print(f"  reordered paths: {[f['path'] for f in reordered]}")

    update_step_state(
        state_store, workflow_id, session_id,
        selected_files=reordered,
    )

    return render_selection_panel(reordered, urls)

# %% ../../nbs/routes/selection.ipynb #0f839f65
def _handle_clear(
    state_store: SQLiteWorkflowStateStore,  # Workflow state store
    provider: LocalFileSystemProvider,  # File system provider
    config: FileBrowserConfig,  # Browser configuration
    workflow_id: str,  # Workflow identifier
    home_path: str,  # Home directory path
    urls: SourceSelectUrls,  # URL bundle
    sess,  # FastHTML session
):  # (selection panel, OOB browser panel, OOB stats panel)
    """Clear all selected files and folders."""
    session_id = get_session_id_from_sess(sess)

    update_step_state(
        state_store, workflow_id, session_id,
        selected_files=[],
        selected_folders=[],
        extraction_results={},
        verified=False,
        committed_audio_paths=[],
    )

    selection = render_selection_panel([], urls)
    browser_oob = _render_oob_browser(
        state_store, provider, config, workflow_id, home_path, urls, session_id, []
    )
    stats_oob = render_stats_panel([], urls)
    stats_oob.attrs["hx-swap-oob"] = "outerHTML"
    return selection, browser_oob, stats_oob

# %% ../../nbs/routes/selection.ipynb #9d362de7
def init_selection_router(
    state_store: SQLiteWorkflowStateStore,  # Workflow state store
    provider: LocalFileSystemProvider,  # File system provider (for OOB browser updates)
    config: FileBrowserConfig,  # Browser configuration (for OOB browser updates)
    workflow_id: str,  # Workflow identifier
    urls: SourceSelectUrls,  # Mutable URL bundle
    home_path: str = "",  # Home directory path
    prefix: str = "/selection",  # Route prefix
) -> Tuple[APIRouter, Dict[str, Callable]]:  # (router, route_dict)
    """Initialize selection queue management routes."""
    router = APIRouter(prefix=prefix)
    _home = home_path or str(Path.home())

    @router
    def remove(sess, path: str = ""):
        """Remove a file from the selection."""
        if not path:
            return render_selection_panel(
                get_step_state(state_store, workflow_id, get_session_id_from_sess(sess)).get("selected_files", []),
                urls
            )
        return _handle_remove(state_store, provider, config, workflow_id, _home, urls, sess, path)

    @router
    async def reorder(request, sess):
        """Reorder selected files via SortableJS."""
        return await _handle_reorder(state_store, workflow_id, urls, request, sess)

    @router
    def clear(sess):
        """Clear all selected files."""
        return _handle_clear(state_store, provider, config, workflow_id, _home, urls, sess)

    routes = {
        "remove": remove,
        "reorder": reorder,
        "clear": clear,
    }

    return router, routes
