# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/cjm-transcription-source-select',
                'doc_host': 'https://cj-mills.github.io',
                'git_url': 'https://github.com/cj-mills/cjm-transcription-source-select',
                'lib_path': 'cjm_transcription_source_select'},
  'syms': {}}
