"""HTML ID constants for the transcription source selection step"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/html_ids.ipynb.

# %% auto #0
__all__ = ['SourceSelectHtmlIds']

# %% ../nbs/html_ids.ipynb #c17b3be3
class SourceSelectHtmlIds:
    """HTML ID constants for the transcription source selection step."""

    @staticmethod
    def as_selector(
        id_str: str  # The HTML ID to convert
    ) -> str:  # CSS selector with # prefix
        """Convert an ID to a CSS selector format."""
        return f"#{id_str}"

    # Main container
    MAIN_CONTAINER = "tss-main-container"

    # Two-column grid (browser + selection, viewport-fitted)
    TWO_COL_GRID = "tss-two-col-grid"

    # File Browser Panel (left column)
    BROWSER_PANEL = "tss-browser-panel"
    BROWSER_BREADCRUMBS = "tss-browser-breadcrumbs"
    BROWSER_FILE_LIST = "tss-browser-file-list"
    BROWSER_ADD_ALL_BTN = "tss-browser-add-all-btn"

    # Selection Panel (right column)
    SELECTION_PANEL = "tss-selection-panel"
    SELECTION_LIST = "tss-selection-list"
    SELECTION_EMPTY = "tss-selection-empty"
    SELECTION_CLEAR_BTN = "tss-selection-clear-btn"

    # Preview Panel
    PREVIEW_PANEL = "tss-preview-panel"
    PREVIEW_CONTENT = "tss-preview-content"
    PREVIEW_TOGGLE = "tss-preview-toggle"
    PREVIEW_EMPTY = "tss-preview-empty"

    # Stats / Verify
    STATS_PANEL = "tss-stats-panel"
    STATS_CONTENT = "tss-stats-content"
    VERIFY_BTN = "tss-verify-btn"
    VERIFY_STATUS = "tss-verify-status"

    # Script runner (OOB container for flash feedback scripts)
    SCRIPT_RUNNER = "tss-script-runner"

    # Keyboard navigation
    GHOST_BROWSER = "tss-ghost-browser"  # Ghost zone wrapping file browser area
    PARENT_SYSTEM_ID = "tss-parent-kb"  # Parent keyboard system for hierarchy
    FB_SYSTEM_ID = "tss_fb-collection"  # File browser VC keyboard system (matches vc_prefix)

    # Keyboard action button IDs
    REMOVE_BTN = "tss-kb-remove-btn"
    TOGGLE_ALL_BTN = "tss-kb-toggle-all-btn"

    @staticmethod
    def _safe_id(
        value: str  # Raw value to sanitize for HTML ID use
    ) -> str:  # Sanitized string safe for HTML IDs
        """Sanitize a string for use in HTML IDs."""
        return value.replace(":", "-").replace("_", "-").replace("/", "-").replace(".", "-")

    @staticmethod
    def file_item(
        file_path: str  # Absolute path to the file
    ) -> str:  # HTML ID for the file item in the browser
        """Generate HTML ID for a file item in the browser list."""
        safe = SourceSelectHtmlIds._safe_id(file_path)
        return f"tss-file-{safe}"

    @staticmethod
    def selection_item(
        file_path: str  # Absolute path to the file
    ) -> str:  # HTML ID for the selection list item
        """Generate HTML ID for a selected file item."""
        safe = SourceSelectHtmlIds._safe_id(file_path)
        return f"tss-sel-{safe}"

    @staticmethod
    def extraction_status(
        file_path: str  # Absolute path to the video file
    ) -> str:  # HTML ID for the extraction status indicator
        """Generate HTML ID for a video file's extraction status."""
        safe = SourceSelectHtmlIds._safe_id(file_path)
        return f"tss-extract-{safe}"
