"""Data models and URL bundles for the transcription source selection step"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/models.ipynb.

# %% auto #0
__all__ = ['SelectedFile', 'ExtractionResult', 'SourceSelectState', 'SourceSelectUrls']

# %% ../nbs/models.ipynb #d0535788
from typing import List, Dict, Optional, Any
from typing_extensions import TypedDict
from dataclasses import dataclass

# %% ../nbs/models.ipynb #8fb8f2e6
class SelectedFile(TypedDict, total=False):
    """A selected audio or video file."""

    path: str  # Absolute path to the file
    filename: str  # Basename of the file
    file_type: str  # "audio" or "video"
    size_bytes: int  # File size in bytes
    duration: Optional[float]  # Duration in seconds (if known)
    format: str  # File extension without dot (e.g. "mp3", "mp4")

# %% ../nbs/models.ipynb #26cfdd4b
class ExtractionResult(TypedDict, total=False):
    """Audio extraction result for a video file."""

    status: str  # "pending", "extracting", "complete", "error"
    audio_path: Optional[str]  # Path to extracted audio (when complete)
    error: Optional[str]  # Error message (when error)
    job_id: Optional[str]  # FFmpeg plugin job ID

# %% ../nbs/models.ipynb #c0240286
class SourceSelectState(TypedDict, total=False):
    """State for the transcription source selection step."""

    selected_files: List[SelectedFile]  # Ordered list of selected files
    current_directory: str  # Current file browser directory path
    browser_state: Dict[str, Any]  # Serialized BrowserState from file-browser library
    extraction_results: Dict[str, ExtractionResult]  # video_path -> extraction result
    verified: bool  # Whether selection has been verified
    committed_audio_paths: List[str]  # Final audio paths for next step

# %% ../nbs/models.ipynb #b4cf4f84
@dataclass
class SourceSelectUrls:
    """URL bundle for transcription source selection routes."""

    # Browser operations
    navigate: str = ""  # Navigate to directory
    select: str = ""  # Toggle file selection (from file browser)

    # Selection operations (Phase 3)
    remove: str = ""  # Remove file from selection
    reorder: str = ""  # Reorder selection (SortableJS)
    clear: str = ""  # Clear all selected files

    # Preview (Phase 4)
    preview: str = ""  # Preview a file (render player)

    # Verify (Phase 5)
    verify: str = ""  # Verify selection + trigger extraction
    extraction_status: str = ""  # Poll extraction status
