"""Utility functions for file type detection, duration formatting, and extension filtering"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/utils.ipynb.

# %% auto #0
__all__ = ['AUDIO_EXTENSIONS', 'VIDEO_EXTENSIONS', 'MEDIA_EXTENSIONS', 'detect_file_type', 'is_media_file', 'format_duration']

# %% ../nbs/utils.ipynb #e1feca3f
from pathlib import Path
from typing import Optional

from cjm_file_discovery.utils.formatting import format_file_size

# %% ../nbs/utils.ipynb #1120035a
AUDIO_EXTENSIONS = frozenset({".mp3", ".wav", ".flac", ".aac", ".ogg", ".m4a", ".wma", ".opus"})
VIDEO_EXTENSIONS = frozenset({".mp4", ".mkv", ".avi", ".mov", ".webm", ".wmv", ".flv"})
MEDIA_EXTENSIONS = AUDIO_EXTENSIONS | VIDEO_EXTENSIONS

# %% ../nbs/utils.ipynb #6fd5a4ae
def detect_file_type(
    file_path: str  # Path to the file
) -> Optional[str]:  # "audio", "video", or None if not a media file
    """Detect whether a file is audio, video, or not a media file based on extension."""
    ext = Path(file_path).suffix.lower()
    if ext in AUDIO_EXTENSIONS:
        return "audio"
    elif ext in VIDEO_EXTENSIONS:
        return "video"
    return None

# %% ../nbs/utils.ipynb #03f21f9e
def is_media_file(
    file_path: str  # Path to the file
) -> bool:  # True if the file has a supported media extension
    """Check if a file has a supported audio or video extension."""
    return Path(file_path).suffix.lower() in MEDIA_EXTENSIONS

# %% ../nbs/utils.ipynb #9f034523
def format_duration(
    seconds: Optional[float]  # Duration in seconds, or None
) -> str:  # Formatted duration string (e.g. "1:23:45" or "42:17")
    """Format a duration in seconds as H:MM:SS or MM:SS."""
    if seconds is None:
        return "--:--"
    total = int(seconds)
    hrs, remainder = divmod(total, 3600)
    mins, secs = divmod(remainder, 60)
    if hrs > 0:
        return f"{hrs}:{mins:02d}:{secs:02d}"
    return f"{mins}:{secs:02d}"
