"""Shared helper functions for the transcription source selection step"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/components/helpers.ipynb.

# %% auto #0
__all__ = ['generate_sortable_init_script']

# %% ../../nbs/components/helpers.ipynb #8acbbdb4
def generate_sortable_init_script(
    container_selector: str = ".sortable",  # CSS selector for sortable containers
    handle_selector: str = ".drag-handle",  # CSS selector for drag handles
    animation_ms: int = 150,  # Animation duration in milliseconds
) -> str:  # JavaScript initialization script
    """Generate Sortable.js initialization script for htmx integration."""
    return f"""
htmx.onLoad(function(content) {{
    var sortables = content.querySelectorAll("{container_selector}");
    for (var i = 0; i < sortables.length; i++) {{
        var sortable = sortables[i];
        var sortableInstance = new Sortable(sortable, {{
            animation: {animation_ms},
            handle: "{handle_selector}",
            onEnd: function (evt) {{
                this.option("disabled", true);
            }}
        }});
        sortable.addEventListener("htmx:afterSwap", function() {{
            sortableInstance.option("disabled", false);
        }});
    }}
}});
"""
