"""Main step renderer combining all panels for the source selection step"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/components/step_renderer.ipynb.

# %% auto #0
__all__ = ['render_source_select_step']

# %% ../../nbs/components/step_renderer.ipynb #d4e5f6a7
from typing import Any, Callable, Dict, List, Optional

from fasthtml.common import Div, H2, P, Script

from cjm_fasthtml_daisyui.utilities.semantic_colors import text_dui

from cjm_fasthtml_tailwind.utilities.spacing import p, m
from cjm_fasthtml_tailwind.utilities.sizing import w, h
from cjm_fasthtml_tailwind.utilities.typography import font_size, font_weight
from cjm_fasthtml_tailwind.utilities.layout import overflow
from cjm_fasthtml_tailwind.utilities.flexbox_and_grid import (
    flex_display, flex_direction, grid_display, grid_cols, gap
)
from cjm_fasthtml_tailwind.core.base import combine_classes

from cjm_fasthtml_viewport_fit.models import ViewportFitConfig
from cjm_fasthtml_viewport_fit.components import render_viewport_fit_script

from cjm_transcription_source_select.models import (
    SourceSelectUrls, SelectedFile, ExtractionResult
)
from ..html_ids import SourceSelectHtmlIds
from .selection_panel import render_selection_panel
from .preview_panel import render_preview_panel
from .stats_panel import render_stats_panel
from .helpers import generate_sortable_init_script

# %% ../../nbs/components/step_renderer.ipynb #f6a7b8c9
# Viewport fit config for the two-column grid
_VIEWPORT_FIT_CONFIG = ViewportFitConfig(
    namespace="tss",
    target_id=SourceSelectHtmlIds.TWO_COL_GRID,
)

def render_source_select_step(
    selected_files: List[SelectedFile],  # Ordered selection
    extraction_results: Dict[str, ExtractionResult],  # video_path -> result
    verified: bool,  # Whether selection is verified
    urls: SourceSelectUrls,  # URL bundle
    render_browser_panel_fn: Callable,  # Browser panel render function from init_browser_router
) -> Div:  # Complete step view
    """Render the complete source selection step."""
    browser_panel = render_browser_panel_fn()
    selection_panel = render_selection_panel(selected_files, urls, extraction_results)
    preview_panel = render_preview_panel(media_src_url=urls.media_src)
    stats_panel = render_stats_panel(selected_files, urls, extraction_results, verified)

    return Div(
        # Two-column layout (browser left, selection right)
        # Height fitted to remaining viewport space via cjm-fasthtml-viewport-fit
        Div(
            Div(browser_panel, cls=combine_classes(
                w.full, h.full, overflow.hidden,
                flex_display, flex_direction.col,
            )),
            Div(selection_panel, cls=combine_classes(w.full, overflow.y.auto)),
            id=SourceSelectHtmlIds.TWO_COL_GRID,
            cls=combine_classes(str(grid_display), grid_cols(1), grid_cols(2).lg, gap(4))
        ),

        # Preview panel
        preview_panel,

        # Stats / verify panel
        stats_panel,

        # SortableJS library + initialization
        Script(src="https://cdn.jsdelivr.net/npm/sortablejs@1.15.0/Sortable.min.js"),
        Script(generate_sortable_init_script()),

        # Viewport fit script (fits two-column grid to remaining viewport)
        render_viewport_fit_script(_VIEWPORT_FIT_CONFIG),

        # Script runner for OOB-triggered JS
        Div(id=SourceSelectHtmlIds.SCRIPT_RUNNER),

        id=SourceSelectHtmlIds.MAIN_CONTAINER,
        cls=combine_classes(w.full, str(flex_display), flex_direction.col, p(4))
    )
